### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by psypersky** [lapwinglabs/google-oauth-agent#3]
Hi, i get this error just requiring the module, im using webpack

```
/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/Users/Psypersky/~/google-oauth-agent/~/superagent/~/formidable/lib/incoming_form.js:3
var crypto = require('crypto');
^
TypeError: require is not a function
    at Object.map../file (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/Users/Psypersky/~/google-oauth-agent/~/superagent/~/formidable/lib/incoming_form.js:3:1)
    at __webpack_require__ (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/webpack/bootstrap a9f9a2c565900158efae:19:1)
    at Object.<anonymous> (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/Users/Psypersky/~/google-oauth-agent/~/superagent/~/formidable/lib/index.js:1:1)
    at __webpack_require__ (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/webpack/bootstrap a9f9a2c565900158efae:19:1)
    at Object.<anonymous> (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/Users/Psypersky/~/google-oauth-agent/~/superagent/lib/node/index.js:7:1)
    at __webpack_require__ (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/webpack/bootstrap a9f9a2c565900158efae:19:1)
    at Object.<anonymous> (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/Users/Psypersky/~/google-oauth-agent/lib/server.js:5:1)
    at __webpack_require__ (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/webpack/bootstrap a9f9a2c565900158efae:19:1)
    at Object.<anonymous> (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/server/endpoint/api/signup/registerOauth.js:16:21)
    at __webpack_require__ (/Users/Psypersky/Documents/projects/ruby-lens/build/webpack:/webpack/bootstrap a9f9a2c565900158efae:19:1)
[1]    5960 segmentation fault  DEBUG=app* gulp dev
```

**Comment by psypersky** [comment]
Looks like super agent uses formidable and formidable uses GENTLY and gentry overwrites the "request" function :/, i changed the lib from superagent to request and it works ok, i can send the PR with those changes if you want

**Comment by matthewmueller** [comment]
hm, i have a feeling it's your webpack configuration doing something funky with modules called request.

**Comment by matthewmueller** [comment]
hm, i have a feeling it's your webpack configuration doing something funky with modules called request.
